FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Sirf frontend ke liye zaroori packages
RUN pip install --no-cache-dir \
    streamlit==1.54.0 \
    requests==2.32.5 \
    python-dotenv==1.2.1

COPY frontend/ ./frontend/
COPY .env* ./

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]